export const articles = [
  {
    id: 1,
    title: "Islam dan Muslim: Beda Tipis, Tapi Bikin Bingung!",
    slug: "islam-dan-muslim-beda-tipis",
    body: "Ketika kita mendengar kata Islam dan Muslim, terkadang ada kebingungan yang muncul. Apakah keduanya sama? Artikel ini menjelaskan perbedaan antara Islam sebagai agama dan Muslim sebagai penganut agama Islam dengan gaya santai.",
    status: "published",
    author: "John Doe",
    timeCreated: "2024-11-18T10:00:00Z",
    category: "Religion",
    tags: ["Islam", "Muslim", "Religion"],
    likes: 150,
    views: 1025,
  },
  {
    id: 2,
    title: "Rahasia Produktivitas: 5 Kebiasaan yang Mengubah Hidup",
    slug: "rahasia-produktivitas",
    body: "Produktivitas adalah kunci keberhasilan di era modern. Dalam artikel ini, kita akan membahas lima kebiasaan penting yang dapat membantu meningkatkan produktivitas Anda, mulai dari manajemen waktu hingga mindfulness.",
    status: "published",
    author: "Jane Smith",
    timeCreated: "2024-11-17T14:30:00Z",
    category: "Personal Development",
    tags: ["Productivity", "Self-Improvement", "Habits"],
    likes: 250,
    views: 1800,
  },
  {
    id: 3,
    title: "Cara Mendapatkan 967 Juta per Bulan dengan Mudah",
    slug: "belajar-tailwind-css",
    body: "Tailwind CSS telah menjadi framework populer untuk membuat desain modern yang responsif. Dalam artikel ini, kami akan memberikan panduan langkah demi langkah untuk memulai menggunakan Tailwind CSS.",
    status: "draft",
    author: "Alice Johnson",
    timeCreated: "2024-11-15T08:15:00Z",
    category: "Web Development",
    tags: ["CSS", "Tailwind", "Frontend"],
    likes: 75,
    views: 600,
  },
  /*
  {
    id: 4,
    title: "Mengenal Teknologi Blockchain: Masa Depan yang Menjanjikan",
    slug: "mengenal-blockchain",
    body: "Blockchain telah menjadi teknologi revolusioner yang memengaruhi berbagai industri, termasuk keuangan, kesehatan, dan logistik. Artikel ini menjelaskan dasar-dasar blockchain dan aplikasinya di dunia nyata.",
    status: "published",
    author: "Robert Brown",
    timeCreated: "2024-11-16T12:45:00Z",
    category: "Technology",
    tags: ["Blockchain", "Technology", "Innovation"],
    likes: 300,
    views: 2500,
  },
  {
    id: 5,
    title: "Resep Kue Cokelat Mudah dan Lezat untuk Pemula",
    slug: "resep-kue-cokelat",
    body: "Siapa yang tidak suka kue cokelat? Dalam artikel ini, kami membagikan resep mudah yang dapat Anda coba di rumah, bahkan jika Anda baru pertama kali memasak.",
    status: "published",
    author: "Mary Lee",
    timeCreated: "2024-11-18T09:00:00Z",
    category: "Food",
    tags: ["Recipe", "Chocolate", "Dessert"],
    likes: 120,
    views: 950,
  },*/
];
